name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: "latest"
          driver: docker
      - name: Set kubectl context for minikube
        run: |
          kubectl config use-context minikube
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run: kubectl apply -f k8s-node-app.yaml
      - name: Inspect Pods
        run: kubectl get pods -o wide
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
